# Generated by Django 4.0.4 on 2022-05-26 07:35

import DraftableApiUiApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_file', models.FileField(upload_to=DraftableApiUiApp.models.input_files_location, verbose_name='Older version File(Left)')),
                ('right_file', models.FileField(upload_to=DraftableApiUiApp.models.input_files_location, verbose_name='Older version File(Right)')),
            ],
        ),
    ]
